/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pjtpdttwvkisbhrhqknh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqdHBkdHR3dmtpc2Jocmhxa25oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3OTMwODgsImV4cCI6MjA3MjM2OTA4OH0.mcwaMSDmXG8s-MnDHrERmeuU-bEMm0JQ0_aG8x6CaJo"